(define (make-interval a b) (cons (min a b) (max a b)))
(define (lower-bound z) (car z))
(define (upper-bound z) (cdr z))

(define (print-interval p)
    (newline)
    (display "(")
    (display (lower-bound p))
    (display ",")
    (display (upper-bound p))
    (display ")"))

(define (sub-interval x y)
    (make-interval (- (lower-bound x) (upper-bound y))
                   (- (upper-bound x) (lower-bound y))))
