(define (fast-mul b n)
    (define (double x) (+ x x))
    (define (halve x) (/ x 2))
    (define (even? x) (= (remainder x 2) 0))
    (define (mul-iter a b n)
        (cond ((= n 0) a)
              ((even? n) (mul-iter a (double b) (/ n 2)))
              (else (mul-iter (+ a b) b (- n 1)))))
    (mul-iter 0 b n))
